package entities;

import java.io.Serializable;

/**
 * The UsageReport class represents a report concerning the usage levels of a park,
 * specifically focusing on the times when the park was not at full capacity. This report
 * it is generated by park managers to monitor and analyze park attendance and utilization
 * across different time periods.
 * 
 * This report includes information such as the month and year of the report, the number of
 * times the park was not full, the name of the park, and the individual 
 * who generated the report. This information can be instrumental in making informed decisions
 * regarding park management and capacity planning for department managers.
 */
public class UsageReport implements Serializable {
    
    private static final long serialVersionUID = 1L;
    private String month; // The month of the report. 
    private String year; // The year of the report.
    private String amount; // The number of visitors in the park during the specified period.
    private String park; // The name of the park the report pertains to.
    private String madeBy; // The name of the park manager who generated the report.
    
    /**
     * Constructs a new UsageReport with specified details about park usage.
     * @param month The month of the report.
     * @param year The year of the report.
     * @param amount The number of visitors in the park during the specified period.
     * @param park The name of the park the report pertains to.
     * @param madeBy The name of the park manager who generated the report.
     */
    public UsageReport(String month, String year, String amount, String park, String madeBy) {
        this.month = month;
        this.year = year;
        this.amount = amount;
        this.park = park;
        this.madeBy = madeBy;
    }

    /**
     * @return The month of the report.
     */
    public String getMonth() {
        return month;
    }

    /**
     * Sets the month of the report.
     * @param month
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * @return The year of the report.
     */
    public String getYear() {
        return year;
    }

    /**
     * Sets the year of the report.
     * @param year
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * @return The number of visitors in the park during the specified period.
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the number of visitors in the park during the specified period.
     * @param amount
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * @return The name of the park the report pertains to.
     */
    public String getPark() {
        return park;
    }

    /**
     * Set the name of the park the report pertains to.
     * @param park
     */
    public void setPark(String park) {
        this.park = park;
    }

    /**
     * @return The name of the park manager who generated the report.
     */
    public String getMadeBy() {
        return madeBy;
    }

    /**
     * Sets the name of the park manager who generated the report.
     * @param madeBy
     */
    public void setMadeBy(String madeBy) {
        this.madeBy = madeBy;
    }
}
